generator:
  class: sfPropelGenerator
  param:
    model_class:           Room
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          room
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, value, name]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
